// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAus3h1IpgnvIDrSxmrePYXdX8XlH0LEUo',
    appId: '1:494271730421:web:ec9a2645a848ecc69b2bbc',
    messagingSenderId: '494271730421',
    projectId: 'smartfarmerprocruitment',
    authDomain: 'smartfarmerprocruitment.firebaseapp.com',
    storageBucket: 'smartfarmerprocruitment.firebasestorage.app',
    measurementId: 'G-0SM29QGDWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt4xADkQ86C9vZq6fG1IzLECZ1Tmiv3Z4',
    appId: '1:494271730421:android:ffad573a06440b759b2bbc',
    messagingSenderId: '494271730421',
    projectId: 'smartfarmerprocruitment',
    storageBucket: 'smartfarmerprocruitment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_eC8dHzt-jHgdsVycjEtTfHYYDxQA718',
    appId: '1:494271730421:ios:3c328bcc34064bff9b2bbc',
    messagingSenderId: '494271730421',
    projectId: 'smartfarmerprocruitment',
    storageBucket: 'smartfarmerprocruitment.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmerProcurement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_eC8dHzt-jHgdsVycjEtTfHYYDxQA718',
    appId: '1:494271730421:ios:3c328bcc34064bff9b2bbc',
    messagingSenderId: '494271730421',
    projectId: 'smartfarmerprocruitment',
    storageBucket: 'smartfarmerprocruitment.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmerProcurement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAus3h1IpgnvIDrSxmrePYXdX8XlH0LEUo',
    appId: '1:494271730421:web:85afae9515ab958e9b2bbc',
    messagingSenderId: '494271730421',
    projectId: 'smartfarmerprocruitment',
    authDomain: 'smartfarmerprocruitment.firebaseapp.com',
    storageBucket: 'smartfarmerprocruitment.firebasestorage.app',
    measurementId: 'G-HJ09NWV8DY',
  );
}
